baseURL = "https://peterampazzo.github.io/project-website-template/"
title = "Beer Data analysis"
description = "What kind of beer drinker are you?"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Lucas Emcken", "Lucas Sylvester", "Lila Meflah"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/peterampazzo/project-website-template"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

