baseURL = "https://luca2618.github.io/social_website/"
title = "Beer Data analysis"
description = "What kind of beer drinker are you? Crazy"
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Lucas Emcken", "Lucas Sylvester", "Lila Meflah"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/luca2618/social_website.git"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

